# Numpy

행렬 및 텐서 연산을 위한 파이썬 라이브러리

In [1]:
import numpy

## Array

In [3]:
import numpy as np #np로 재정의

a = np.array([1,2,3]) # 1차원 array [1,2,3] 생성
print(type(a)) # numpy.ndarray
print(a.shape) # a의 shape -> 튜플 리턴 => element가 하나일 때 튜플 표현방식: (3,)
print(a[0], a[1], a[2]) # 인덱스로 접근
a[0] = 5 # 수정
print(a)

b = np.array([[1,2,3],[4,5,6]]) # 2행 3열
print(b.shape) # (2,3)
print(b[0, 0], b[0, 1], b[1, 0]) # b[0,0] == b[0][0]
print(b[0][0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
1


In [7]:
import numpy as np

# 모든 값이 0인 2x2 array 생성
a = np.zeros([2,2]) 
print(a)

# 모든 값이 1인 1x2 array 생성
b = np.ones((1,2)) 
print(b)

# 모든 값이 7인 2x2 array 생성
c = np.full((2,2), 7) 
print(c)

# 2x2 단위행렬(Identity matrix) 생성
d = np.eye(2) 
print(d)

# 0~1 랜덤 값을 가지는 2x2 array 생성
e = np.random.random((2,2)) 
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.59816974 0.985647  ]
 [0.48690671 0.4430534 ]]


## Array Slicing

배열의 일부를 가져다 오는 방법 -> :사용

In [11]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 첫번째 행의 처음부터 2 앞까지(0,1), 두번째 행에서
# 1부터 3 앞까지(1,2)의 값들을 떠와 b에 할당.
# 따라서 b 는 다음과 같은 2x2 array:
# [[2 3]
# [6 7]]

b = a[:2, 1:3] # a의 0,1행 1,2열 추출
print(b)

print(a[0, 1])
b[0, 0] = 77 # b[0,0] == a[0,1]
print(a[0, 1])
# Slicing을 한다고 해서 값을 복사해가는 것이 아니므로
# 값의 변화가 동시에 일어남

[[2 3]
 [6 7]]
2
77


In [12]:
import numpy as np
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :] # 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## Array Indexing

In [16]:
import numpy as np
# 2차원 배열(3x2) 생성
# [[ 1 2]
# [ 3 4]
# [ 5 6]]

a = np.array([[1, 2], [3, 4], [5, 6]])

# [1 4 5] 1차원 행렬(3,)을 얻는 두 가지 방법
b = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(b)
c = np.array(a[[0, 1, 2], [0, 1, 0]]) # a[[행에 대한 리스트],[열에 대한 리스트]]
print(c)
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# [2 2] 1차원 행렬(2,)을 얻는 두 가지 방법
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [19]:
import numpy as np
# 2차원 배열(4x3) 생성
# [[ 1 2 3]
# [ 4 5 6]
# [ 7 8 9]
# [ 10 11 12]]
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

print(np.arange(4))
print(a[np.arange(4),b]) # arange(parameter) ->파라미터가 무조건 int 여야함..
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # == a[[0,1,2,3],[0,2,0,1]] => [1 6 7 11]
a[np.arange(4), b] += 10 # 각각의 1,6,7,11 에 10 더하기
print(a) # array([[11, 2, 3],
                #[ 4, 5, 16],
                #[17, 8, 9],
                #[10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 1 2 3]
[ 1  6  7 11]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## 데이터 타입

In [20]:
import numpy as np

x = np.array([1, 2])
print(x.dtype) # prints “int64”

x = np.array([1.0, 2.0])
print(x.dtype) # “float64”

x = np.array([1, 2], dtype=np.int64) # 데이터타입 명시
print(x.dtype) # “int64”

int64
float64
int64


## Array 연산

연산하려는 두 개의 타입이 같아야 한다.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum
# [[ 6.0 8.0]
# [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference
# [[-4.0 -4.0]
# [-4.0 -4.0]]
print(x – y) 
print(np.subtract(x, y)) 

#Elementwise square root
print(np.sqrt(x))

#Elementwise product
print(x * y)
print(np.multiply(x, y))

# Elementwise division
print(x / y)
print(np.divide(x, y))

### Dot product

In [42]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# v · w = 219
# 두가지 방법
print(v.dot(w))
print(np.dot(v, w))

# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))

# 매트릭스 / 매트릭스 곱;
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Sum

In [26]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
print(np.sum(x))

# 모든 원소의 합
print(np.sum(x, axis=0)) # 각 열의 합
print(np.sum(x, axis=1)) # 각 행의 합

10
[4 6]
[3 7]


In [28]:
import numpy as np 
a = np.ones((2,3,4))
# a.shape
print(np.sum(a))
print(np.sum(a, axis=0)) # 0번째 축이 없어진다고 생각 -> (2,3,4) => (3,4)
print(np.sum(a, axis=0).shape)
print(np.sum(a, axis=1)) # 1번째 축이 없어진다고 생각 -> (2,3,4) => (2,4)
print(np.sum(a, axis=1).shape)

24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
(3, 4)
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
(2, 4)


### Transpose

In [29]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)  # 전치행렬 (Transposed mat.)

v = np.array([1,2,3])
print(v)  # prints “[1 2 3]”
print(v.T)  # prints “[1 2 3]” -> 벡터는 바뀌지 않는다

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

x의 각각의 행에 v를 더하는 방법

In [31]:
# 첫번째
import numpy as np
x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10,11,12]])
v = np.array([1,0,1])

# x의 각 행에 v를 더하고자 함.
y = np.empty_like(x) # x와 같은 shape의 빈 매트릭스 만들기
# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4): # 행 개수 == x.shape[0]
    y[i, :] = x[i, :] + v # y[i,:] => y[i]로 쓸 수 있다.

# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[4611686018427387904 4611686018427387904 4611686018427387904]
 [4611686018427387904 4611686018427387904 4611686018427387904]
 [4611686018427387904 4611686018427387904 4611686018427387904]
 [4611686018427387904 4611686018427387904 4611686018427387904]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [32]:
# 두번째
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함

print(vv)
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### 세번째 -> Broadcasting

In [35]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]) # 4*3 행렬
v = np.array([1,0,1]) # [1,3] 벡터

# 브로드캐스팅을 사용하여 x의 각 행에 v값을 더함
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [41]:
# Broadcas([[1,-1],[2,0]])
b = np.array([1,0])ting 가능, 불가능 여부
# (4,3) (1,3) => O
# (3,4) (3,1) => O
# (3,4) (3,2) => X
# (2,3,4) (1,3,1) => O
# (4,3) (3,) => O
# (3,4) (3,) => X
# (3,4) (3,1) => O

#(3,) -> (3,1) 하는 방법
a = np.array([1,2,3])
a1 = a.reshape([3,1])
print(a1.shape) # => (3,1)
a2 = a[:,None]
print(a2.shape)

(3, 1)
(3, 1)


## 연습문제2

In [46]:
import numpy as np

x = np.array([[1,1],[2,1]])
y = np.array([15,25])
x_i = np.linalg.inv(x)
print(x_i.dot(y))

[10.  5.]


## pickle

## 과제 3 - and_op.py

In [72]:
import numpy as np

x1 = np.array([0,0])
x2 = np.array([0,1])
x3 = np.array([1,0])
x4 = np.array([1,1])
W = np.array([[1,-1],[2,0]])
b = np.array([1,0])

print(np.argmax(W.dot(x1)+b))
print(np.argmax(W.dot(x2)+b))
print(np.argmax(W.dot(x3)+b))
print(np.argmax(W.dot(x4)+b))

0
0
0
1


{1, 2, 3, 4}